# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Messengar' do
  use_frameworks!
  
# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Google Sign IN
pod 'GoogleSignIn'

end
