# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Messengar' do
  use_frameworks!
  
# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Google Sign IN
pod 'GoogleSignIn'

pod 'MessageKit'
pod 'JGProgressHUD', '~> 2.1'
pod 'RealmSwift'
pod 'SDWebImage'

end
